# Generated by Django 4.0.5 on 2022-07-02 13:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('imdb_title_id', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=150)),
                ('original_title', models.CharField(max_length=150)),
                ('year', models.CharField(blank=True, max_length=50, null=True)),
                ('date_published', models.CharField(blank=True, max_length=100, null=True)),
                ('genre', models.CharField(blank=True, max_length=255, null=True)),
                ('duration', models.CharField(blank=True, max_length=50, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('language', models.CharField(blank=True, max_length=255, null=True)),
                ('director', models.CharField(blank=True, max_length=255, null=True)),
                ('writer', models.CharField(blank=True, max_length=255, null=True)),
                ('production_company', models.CharField(blank=True, max_length=255, null=True)),
                ('actors', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('avg_vote', models.CharField(blank=True, max_length=50, null=True)),
                ('vote', models.CharField(blank=True, max_length=50, null=True)),
                ('budget', models.CharField(blank=True, max_length=100, null=True)),
                ('usa_gross_income', models.CharField(blank=True, max_length=100, null=True)),
                ('worldwide_gross_income', models.CharField(blank=True, max_length=100, null=True)),
                ('metascore', models.CharField(blank=True, max_length=100, null=True)),
                ('reviews_from_users', models.CharField(blank=True, max_length=100, null=True)),
                ('reviews_from_critics', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'movies',
                'ordering': ['-date_published'],
            },
        ),
    ]
