# Generated by Django 4.0.5 on 2022-07-03 15:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='id',
            field=models.TextField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
